version: "3"


services:
  postgres-service:
    image: postgres
    container_name: process-db-postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "090821"
      POSTGRES_DB: "process-db"
    ports:
      - "5432:5432"
    networks:
          - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin-container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "lupesms97@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "LuPe0129**"
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
          - postgres-compose-network

networks:
  default:
    external: true
  postgres-compose-network:
    driver: bridge



