version: "3.8"

services:
  postgres-service:
    image: postgres
    container_name: process-db-postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "090821"
      POSTGRES_DB: "process-db"
    ports:
      - "5432:5432"
    networks:
      - spring-boot-postgres-network
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - API_SECURITY_TOKEN_SECRET=Helena090821
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/process-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=090821
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS=true
      - SERVER_PORT=8080
    networks:
      - spring-boot-postgres-network
    depends_on:
      - postgres-service
networks:
  spring-boot-postgres-network:
    driver: bridge

